version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  event-db:
    image: postgres:15
    container_name: event-db
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_db
    ports:
      - "5434:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  ticket-db:
    image: postgres:15
    container_name: ticket-db
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket_db
    ports:
      - "5435:5432"
    volumes:
      - ticket-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  user-db-data:
  event-db-data:
  ticket-db-data:
