apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
data:
  USER_DB_PASSWORD: cGFzc3dvcmQ=
  EVENT_DB_PASSWORD: cGFzc3dvcmQ=
  TICKET_DB_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: bGQ7ZmtzYXloZ3RpcmRvaW9kc2E0NzkwOHQ4OTA4b28zNDBwMzl3NDV0NDA5M2Rvc2tm  # base64 of your JWT secret string